version: "3.9"
services:
  app:
    container_name: app
    build:
      dockerfile: ./app/Dockerfile
      context: .
    ports:
      - 50000:5050
      - 50001:50001
      - 443:8081
    volumes:
      - .:/opt/app/api
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_DB=db  
      - DB_AWAIT_SECONDS=3
      - DAYS_TO_SAVE_SENSORSDATA=${DAYS_TO_SAVE_SENSORSDATA}
      - LOGIN_DELAY_MAX_MILLIS=${LOGIN_DELAY_MAX_MILLIS}

    depends_on:
      - db
    networks:
      - backend
  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    networks:
      - backend

volumes:
  database:

networks:
  frontend:
  backend:
    driver: bridge
